### ISSUE TITLE
When creating a new trip, that trip does not show up in a user's trip list on home page

### ISSUE THREAD

**Issue by krhae** [lorenzodb1/trippi-ubc-cs304-project#13]
Think the plan table needs to be updated

<img width="554" alt="screen shot 2016-06-13 at 19 59 58" src="https://cloud.githubusercontent.com/assets/3385725/16029894/7ecba834-31a1-11e6-9929-5b518b7a3a68.png">
<img width="347" alt="screen shot 2016-06-13 at 20 00 14" src="https://cloud.githubusercontent.com/assets/3385725/16029895/7eceb5ce-31a1-11e6-8e54-1698e286d44a.png">
<img width="738" alt="screen shot 2016-06-13 at 20 00 43" src="https://cloud.githubusercontent.com/assets/3385725/16029905/8a854bda-31a1-11e6-9e84-b41ac7bd5f56.png">

**Comment by SamirMarin** [comment]
this works now.. It link the plan table to the trips.

**Comment by SamirMarin** [comment]
to the user I mean so if you create a trip it will appear on the list of trips
