### ISSUE TITLE
Work on providing a message to indicate login failed.. USER name or password wrong.

### ISSUE THREAD

**Issue by SamirMarin** [lorenzodb1/trippi-ubc-cs304-project#2]
right now if login fails we are redirected to the main login page again. But the user gets no message saying what happened it just redirects.. This redirect  happens in the HomeController.php. We would want to provide a message on that same page that says login failed.. "Username or password are wrong" or something.

**Comment by krhae** [comment]
TODO: look up error handling in bootstrap, and handle the failure case in signIn in HomeController

**Comment by krhae** [comment]
Added error message on failed login attempt.
