### ISSUE TITLE
List all trips.. and functionality to to make queries on what trip you want to see..

### ISSUE THREAD

**Issue by SamirMarin** [lorenzodb1/trippi-ubc-cs304-project#5]
This is a page that you can view all trips and then have ways to filter this trips to see certain criteria.. this will require a view.. controller and perhaps some queries though I think a lot are build in the trip.php file.

**Comment by krhae** [comment]
Can't this be solved by using the "search" page which has the queries tab?

**Comment by SamirMarin** [comment]
yeah.. We solved this with search tab in terms of doing queries on trips!
