### ISSUE TITLE
figure out those complex queries we still need and how we can write them.

### ISSUE THREAD

**Issue by SamirMarin** [lorenzodb1/trippi-ubc-cs304-project#8]
I think we are still missing a lot of idea on how we are going to implement those more complex queries and put them to use.. So myb thinking about how we can do them and written a few with the idea of what input would come from he ui to run them.

**Comment by krhae** [comment]
- [x] Division Query
- [x] Nested aggregation with group-by
- [x] Delete operation
- [x] Update operation

**Comment by lorenzodb1** [comment]
Trip->searchMostLoyalCompanion has both division and nested aggregation with group-by
